### ISSUE TITLE
Can't fetch Single Types

### ISSUE THREAD

**Issue by Shackless** [rixw/strapi-utils#76]
Hi, 

I have a Single Type `Homepage` defined in Strapi. When I try to call `fetchSingle()` to retrieve it, I get a 404. 

```ts
await client.fetchSingle<Homepage>("homepage", { populate: '*' })
```

I can see in the debug logs that it's actually calling `/api/homepages` instead of `/api/homepage`, so it's using the pluralized name. How can I get around this? I added the content type to the client by just using the singular name. 

```ts
export const client = new StrapiClient({
	url: PUBLIC_STRAPI_HOST,
	jwt: STRAPI_APIKEY,
	contentTypes: ["homepage"],
	debug: true,
});
```

**Comment by rixw** [comment]
Sorry for the slow response. The reason is that if you specify a value in `contentTypes` as a string, it is assumed to be a collection type. For a single type, use the longer form JSON options:

```
export const client = new StrapiClient({
	url: PUBLIC_STRAPI_HOST,
	jwt: STRAPI_APIKEY,
	contentTypes: [
          {
            id: 'homepage.homepage',
            singularName: 'homepage',
            path: '/api/homepage',
          },
        ],
	debug: true,
});
```

I'll clarify in README.
